# 데이터 불러오기 및 전처리

In [84]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [85]:
# 파일 불러오기
df=pd.read_excel('최종데이터.xlsx',index_col='영화명')
df.head()

,개봉일,매출액,매출액점유율,관객수,스크린수,상영횟수,대표국적,등급,장르,제작연도,유형,편당관객수,스크린당관객수,네티즌평점,평론가평점,긍정확률
영화명,,,,,,,,,,,,,,,,
보헤미안 랩소디,2018-10-31,25.105423,0.044,9224582,1179,204537,미국,12세이상관람가,드라마,2018,장편,45.099821,7824.072943,9.42,6.14,0.73
공작,2018-08-08,24.479543,0.024,4974520,1317,99001,한국,12세이상관람가,드라마,2017,장편,50.247169,3777.160213,6.83,6.93,0.20
국가부도의 날,2018-11-28,24.152268,0.017,3747952,1180,100804,한국,12세이상관람가,드라마,2018,장편,37.180588,3176.230508,8.12,6.50,0.79
코코,2018-01-11,24.044174,0.015,3510017,1177,85925,미국,전체관람가,애니메이션,2017,장편,40.849776,2982.172472,9.32,8.00,0.64
아쿠아맨,2018-12-19,24.139493,0.017,3491857,1285,54505,미국,12세이상관람가,액션,2018,장편,64.064893,2717.398444,8.36,6.83,0.69

In [86]:
# 날짜를 int로 바꾸기
from datetime import date
df['개봉일'] = df['개봉일'].apply(lambda x: x.strftime('%Y%m%d'))

df['개봉일'] = df['개봉일'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 812 entries, 보헤미안 랩소디 to 일론 머스크: 리얼 아이언맨
Data columns (total 16 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   개봉일      812 non-null    int32
 1   매출액      812 non-null    float64
 2   매출액점유율   812 non-null    float64
 3   관객수      812 non-null    int64
 4   스크린수     812 non-null    int64
 5   상영횟수     812 non-null    int64
 6   대표국적     812 non-null    object
 7   등급       812 non-null    object
 8   장르       812 non-null    object
 9   제작연도     812 non-null    int64
 10  유형       812 non-null    object
 11  편당관객수    812 non-null    float64
 12  스크린당관객수  812 non-null    float64
 13  네티즌평점    812 non-null    float64
 14  평론가평점    812 non-null    float64
 15  긍정확률     812 non-null    float64
dtypes: float64(7), int32(1), int64(4), object(4)
memory usage: 104.7+ KB

In [87]:
# object열을 바꿔주기
# 1) 등급
df['등급 '].value_counts()
df['등급 ']=df['등급 '].map({'전체관람가':0,'12세이상관람가':1,'12세관람가':1,'15세이상관람가':2,'청소년관람불가':3})

In [88]:
df.head()

,개봉일,매출액,매출액점유율,관객수,스크린수,상영횟수,대표국적,등급,장르,제작연도,유형,편당관객수,스크린당관객수,네티즌평점,평론가평점,긍정확률
영화명,,,,,,,,,,,,,,,,
보헤미안 랩소디,20181031,25.105423,0.044,9224582,1179,204537,미국,1,드라마,2018,장편,45.099821,7824.072943,9.42,6.14,0.73
공작,20180808,24.479543,0.024,4974520,1317,99001,한국,1,드라마,2017,장편,50.247169,3777.160213,6.83,6.93,0.20
국가부도의 날,20181128,24.152268,0.017,3747952,1180,100804,한국,1,드라마,2018,장편,37.180588,3176.230508,8.12,6.50,0.79
코코,20180111,24.044174,0.015,3510017,1177,85925,미국,0,애니메이션,2017,장편,40.849776,2982.172472,9.32,8.00,0.64
아쿠아맨,20181219,24.139493,0.017,3491857,1285,54505,미국,1,액션,2018,장편,64.064893,2717.398444,8.36,6.83,0.69

In [89]:
df.columns

Index(['개봉일', '매출액 ', '매출액점유율', '관객수 ', '스크린수 ', '상영횟수 ', '대표국적 ', '등급 ', '장르',
       '제작연도', '유형', '편당관객수', '스크린당관객수', '네티즌평점', '평론가평점', '긍정확률'],
      dtype='object')

In [90]:
# 2) 대표국적, 유형, 장르 레이블 인코딩
from sklearn.preprocessing import LabelEncoder
# 유형, 장르, 대표국적에 레이블 인코딩
le=LabelEncoder()
df['대표국적 ']=le.fit_transform(df['대표국적 '].values)

In [91]:
df['유형']=le.fit_transform(df['유형'].values)
df['장르']=le.fit_transform(df['장르'].values)

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 812 entries, 보헤미안 랩소디 to 일론 머스크: 리얼 아이언맨
Data columns (total 16 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   개봉일      812 non-null    int32
 1   매출액      812 non-null    float64
 2   매출액점유율   812 non-null    float64
 3   관객수      812 non-null    int64
 4   스크린수     812 non-null    int64
 5   상영횟수     812 non-null    int64
 6   대표국적     812 non-null    int32
 7   등급       812 non-null    int64
 8   장르       812 non-null    int32
 9   제작연도     812 non-null    int64
 10  유형       812 non-null    int32
 11  편당관객수    812 non-null    float64
 12  스크린당관객수  812 non-null    float64
 13  네티즌평점    812 non-null    float64
 14  평론가평점    812 non-null    float64
 15  긍정확률     812 non-null    float64
dtypes: float64(7), int32(4), int64(5)
memory usage: 95.2+ KB

In [93]:
# null값 확인
df.isnull().sum()

개봉일        0
매출액        0
매출액점유율     0
관객수        0
스크린수       0
상영횟수       0
대표국적       0
등급         0
장르         0
제작연도       0
유형         0
편당관객수      0
스크린당관객수    0
네티즌평점      0
평론가평점      0
긍정확률       0
dtype: int64

In [94]:
df.columns

Index(['개봉일', '매출액 ', '매출액점유율', '관객수 ', '스크린수 ', '상영횟수 ', '대표국적 ', '등급 ', '장르',
       '제작연도', '유형', '편당관객수', '스크린당관객수', '네티즌평점', '평론가평점', '긍정확률'],
      dtype='object')

In [95]:
# df['관객수 ']=np.log(df['관객수 '])

In [96]:
df.head()

,개봉일,매출액,매출액점유율,관객수,스크린수,상영횟수,대표국적,등급,장르,제작연도,유형,편당관객수,스크린당관객수,네티즌평점,평론가평점,긍정확률
영화명,,,,,,,,,,,,,,,,
보헤미안 랩소디,20181031,25.105423,0.044,9224582,1179,204537,8,1,6,2018,1,45.099821,7824.072943,9.42,6.14,0.73
공작,20180808,24.479543,0.024,4974520,1317,99001,32,1,6,2017,1,50.247169,3777.160213,6.83,6.93,0.20
국가부도의 날,20181128,24.152268,0.017,3747952,1180,100804,32,1,6,2018,1,37.180588,3176.230508,8.12,6.50,0.79
코코,20180111,24.044174,0.015,3510017,1177,85925,8,0,13,2017,1,40.849776,2982.172472,9.32,8.00,0.64
아쿠아맨,20181219,24.139493,0.017,3491857,1285,54505,8,1,14,2018,1,64.064893,2717.398444,8.36,6.83,0.69

In [97]:
df.columns

Index(['개봉일', '매출액 ', '매출액점유율', '관객수 ', '스크린수 ', '상영횟수 ', '대표국적 ', '등급 ', '장르',
       '제작연도', '유형', '편당관객수', '스크린당관객수', '네티즌평점', '평론가평점', '긍정확률'],
      dtype='object')

## 분류 모델을 위해 범주형 변수로 만들기

In [98]:
df.loc[df['네티즌평점']>=8.0,'result']=1
df.loc[df['네티즌평점']<8.0,'result']=0
df

,개봉일,매출액,매출액점유율,관객수,스크린수,상영횟수,대표국적,등급,장르,제작연도,유형,편당관객수,스크린당관객수,네티즌평점,평론가평점,긍정확률,result
영화명,,,,,,,,,,,,,,,,,
보헤미안 랩소디,20181031,25.105423,0.044,9224582,1179,204537,8,1,6,2018,1,45.099821,7824.072943,9.42,6.14,0.73,1.0
공작,20180808,24.479543,0.024,4974520,1317,99001,32,1,6,2017,1,50.247169,3777.160213,6.83,6.93,0.20,0.0
국가부도의 날,20181128,24.152268,0.017,3747952,1180,100804,32,1,6,2018,1,37.180588,3176.230508,8.12,6.50,0.79,1.0
코코,20180111,24.044174,0.015,3510017,1177,85925,8,0,13,2017,1,40.849776,2982.172472,9.32,8.00,0.64,1.0
아쿠아맨,20181219,24.139493,0.017,3491857,1285,54505,8,1,14,2018,1,64.064893,2717.398444,8.36,6.83,0.69,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
라이브 하드,20210225,14.480809,0.000,237,10,92,32,2,6,2020,1,2.576087,23.700000,8.86,6.00,0.64,1.0
윙스 오버 에베레스트,20210930,13.874534,0.000,174,10,10,24,2,14,2019,1,17.400000,17.400000,6.17,0.00,0.46,0.0
"킬링,",20210407,13.908463,0.000,125,4,53,23,3,6,2018,1,2.358491,31.250000,8.78,7.83,0.13,1.0
서유기: 재세요왕,20210930,13.883636,0.000,123,20,22,24,0,13,2020,1,5.590909,6.150000,5.67,6.00,0.27,0.0
일론 머스크: 리얼 아이언맨,20210211,13.384728,0.000,101,1,9,20,0,5,2018,1,11.222222,101.000000,5.32,0.00,0.24,0.0

# 결정 트리 모델에 적용

In [99]:
X=df.drop(['네티즌평점','result'],axis=1)
y=df['result']

In [100]:
X.columns

Index(['개봉일', '매출액 ', '매출액점유율', '관객수 ', '스크린수 ', '상영횟수 ', '대표국적 ', '등급 ', '장르',
       '제작연도', '유형', '편당관객수', '스크린당관객수', '평론가평점', '긍정확률'],
      dtype='object')

In [101]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [102]:
tree=DecisionTreeClassifier(random_state=0,max_depth=5)
tree.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5, random_state=0)

In [103]:
pred=tree.predict(X_test)

In [104]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,pred)
print(acc)

0.7540983606557377

In [105]:
train_scores,test_scores=list(),list()

In [106]:
for i in range(1,20):
    DT1=DecisionTreeClassifier(max_depth=i)
    # 깊이를 증가시키면서 의사결정나무 모델 적합
    DT1.fit(X_train,y_train)
    
    # training dataset 정확도 평가
    train_att=DT1.predict(X_train)
    train_acc=accuracy_score(y_train,train_att)
    train_scores.append(train_acc)
    
    # test data 정확도 평가
    test_att=DT1.predict(X_test)
    test_acc=accuracy_score(y_test,test_att)
    test_scores.append(test_acc)
    
    # Train 정확도와 Test 정확도를 depth 개수에 따른 정확도 확인
    print('>%d train : %.3f, test : %.3f' % (i,train_acc,test_acc))

>1 train : 0.771, test : 0.738
>2 train : 0.771, test : 0.738
>3 train : 0.790, test : 0.738
>4 train : 0.798, test : 0.738
>5 train : 0.820, test : 0.754
>6 train : 0.840, test : 0.742
>7 train : 0.864, test : 0.734
>8 train : 0.879, test : 0.758
>9 train : 0.914, test : 0.725
>10 train : 0.938, test : 0.721
>11 train : 0.963, test : 0.730
>12 train : 0.984, test : 0.713
>13 train : 0.991, test : 0.713
>14 train : 0.998, test : 0.721
>15 train : 1.000, test : 0.717
>16 train : 1.000, test : 0.713
>17 train : 1.000, test : 0.730
>18 train : 1.000, test : 0.738
>19 train : 1.000, test : 0.734

In [107]:
tree.feature_importances_

array([0.01287389, 0.        , 0.00735019, 0.        , 0.05198858,
       0.01777406, 0.        , 0.0450338 , 0.0691641 , 0.00735019,
       0.        , 0.02867952, 0.06644746, 0.03075292, 0.6625853 ])

In [108]:
pd.DataFrame(tree.feature_importances_.reshape((1,-1)), index=['feature_importance'])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
feature_importance,0.012874,0.0,0.00735,0.0,0.051989,0.017774,0.0,0.045034,0.069164,0.00735,0.0,0.02868,0.066447,0.030753,0.662585

In [109]:
X.columns

Index(['개봉일', '매출액 ', '매출액점유율', '관객수 ', '스크린수 ', '상영횟수 ', '대표국적 ', '등급 ', '장르',
       '제작연도', '유형', '편당관객수', '스크린당관객수', '평론가평점', '긍정확률'],
      dtype='object')

In [110]:
df.columns

Index(['개봉일', '매출액 ', '매출액점유율', '관객수 ', '스크린수 ', '상영횟수 ', '대표국적 ', '등급 ', '장르',
       '제작연도', '유형', '편당관객수', '스크린당관객수', '네티즌평점', '평론가평점', '긍정확률', 'result'],
      dtype='object')

In [111]:
a=pd.DataFrame(tree.feature_importances_.reshape((1,-1)),columns=X.columns, index=['feature_importance'])

In [112]:
b=a.T
b=b.sort_values(by='feature_importance',ascending=False)

In [113]:
b

         feature_importance
긍정확률               0.662585
장르                 0.069164
스크린당관객수            0.066447
스크린수               0.051989
등급                 0.045034
평론가평점              0.030753
편당관객수              0.028680
상영횟수               0.017774
개봉일                0.012874
매출액점유율             0.007350
제작연도               0.007350
매출액                0.000000
관객수                0.000000
대표국적               0.000000
유형                 0.000000

- 이를 통해 다음과 같은 결과가 나왔다.
    - 긍정확률, 장르, 스크린당 관객수, 스크린수,등급,평론가 평점 등 순으로 변수의 중요도가 나왔다.
    
## 그렇다면 변수중요도가 0인 것들을 제외하고 다시 돌려보자

In [114]:
df.columns.drop(['네티즌평점','result'])

Index(['개봉일', '매출액 ', '매출액점유율', '관객수 ', '스크린수 ', '상영횟수 ', '대표국적 ', '등급 ', '장르',
       '제작연도', '유형', '편당관객수', '스크린당관객수', '평론가평점', '긍정확률'],
      dtype='object')

- 확인결과 매출액, 관객수, 대표국적, 유형이 평가에 영향을 미치지 않는 것으로 판단됨. 그러므로 제거하고 다시 모델링을 돌려본다

In [115]:
df=df.drop(['매출액 ','관객수 ','대표국적 ','유형'],axis=1)
df.head()

,개봉일,매출액점유율,스크린수,상영횟수,등급,장르,제작연도,편당관객수,스크린당관객수,네티즌평점,평론가평점,긍정확률,result
영화명,,,,,,,,,,,,,
보헤미안 랩소디,20181031,0.044,1179,204537,1,6,2018,45.099821,7824.072943,9.42,6.14,0.73,1.0
공작,20180808,0.024,1317,99001,1,6,2017,50.247169,3777.160213,6.83,6.93,0.20,0.0
국가부도의 날,20181128,0.017,1180,100804,1,6,2018,37.180588,3176.230508,8.12,6.50,0.79,1.0
코코,20180111,0.015,1177,85925,0,13,2017,40.849776,2982.172472,9.32,8.00,0.64,1.0
아쿠아맨,20181219,0.017,1285,54505,1,14,2018,64.064893,2717.398444,8.36,6.83,0.69,1.0

In [116]:
df.columns

Index(['개봉일', '매출액점유율', '스크린수 ', '상영횟수 ', '등급 ', '장르', '제작연도', '편당관객수',
       '스크린당관객수', '네티즌평점', '평론가평점', '긍정확률', 'result'],
      dtype='object')

In [117]:
X=df.drop(['네티즌평점','result'],axis=1)
y=df['result']

In [118]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
tree=DecisionTreeClassifier(random_state=0,max_depth=5)
tree.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5, random_state=0)

In [119]:
pred=tree.predict(X_test)

In [120]:
from sklearn.metrics import accuracy_score
acc2=accuracy_score(y_test,pred)
print(acc2)

0.7581967213114754

In [121]:
tree.feature_importances_

array([0.01287389, 0.        , 0.05198858, 0.01777406, 0.0450338 ,
       0.0691641 , 0.        , 0.04337989, 0.06644746, 0.03075292,
       0.6625853 ])

In [122]:
pd.DataFrame(tree.feature_importances_.reshape((1,-1)), index=['feature_importance'])

,0,1,2,3,4,5,6,7,8,9,10
feature_importance,0.012874,0.0,0.051989,0.017774,0.045034,0.069164,0.0,0.04338,0.066447,0.030753,0.662585

In [123]:
a2=pd.DataFrame(tree.feature_importances_.reshape((1,-1)),columns=X.columns, index=['feature_importance'])
a2

,개봉일,매출액점유율,스크린수,상영횟수,등급,장르,제작연도,편당관객수,스크린당관객수,평론가평점,긍정확률
feature_importance,0.012874,0.0,0.051989,0.017774,0.045034,0.069164,0.0,0.04338,0.066447,0.030753,0.662585

In [124]:
b2=a2.T
b2=b2.sort_values(by='feature_importance',ascending=False)
b2

         feature_importance
긍정확률               0.662585
장르                 0.069164
스크린당관객수            0.066447
스크린수               0.051989
등급                 0.045034
편당관객수              0.043380
평론가평점              0.030753
상영횟수               0.017774
개봉일                0.012874
매출액점유율             0.000000
제작연도               0.000000

In [126]:
b

         feature_importance
긍정확률               0.662585
장르                 0.069164
스크린당관객수            0.066447
스크린수               0.051989
등급                 0.045034
평론가평점              0.030753
편당관객수              0.028680
상영횟수               0.017774
개봉일                0.012874
매출액점유율             0.007350
제작연도               0.007350
매출액                0.000000
관객수                0.000000
대표국적               0.000000
유형                 0.000000

매출액, 관객수, 대표국적, 유형을 제외하고 다시 모델링을 시행해 중요도를 확인한 결과, 이전과 대개 비슷한 결과가 나왔다.

## 긍정확률의 경우가 66%의 영향력을 미치게 되는데, 엄청난 영향을 미치는 긍정확률을 제거하고 다시 평가를 해보면?

In [152]:
df=pd.read_excel('최종데이터.xlsx',index_col='영화명')

from datetime import date
df['개봉일'] = df['개봉일'].apply(lambda x: x.strftime('%Y%m%d'))
df['개봉일'] = df['개봉일'].astype(int)


# object열을 바꿔주기
# 1) 등급
df['등급 '].value_counts()
df['등급 ']=df['등급 '].map({'전체관람가':0,'12세이상관람가':1,'12세관람가':1,'15세이상관람가':2,'청소년관람불가':3})

# 2) 대표국적, 유형, 장르 레이블 인코딩
from sklearn.preprocessing import LabelEncoder
# 유형, 장르, 대표국적에 레이블 인코딩
le=LabelEncoder()
df['대표국적 ']=le.fit_transform(df['대표국적 '].values)

df['유형']=le.fit_transform(df['유형'].values)
df['장르']=le.fit_transform(df['장르'].values)

df.loc[df['네티즌평점']>=8.0,'result']=1
df.loc[df['네티즌평점']<8.0,'result']=0

In [153]:
df

,개봉일,매출액,매출액점유율,관객수,스크린수,상영횟수,대표국적,등급,장르,제작연도,유형,편당관객수,스크린당관객수,네티즌평점,평론가평점,긍정확률,result
영화명,,,,,,,,,,,,,,,,,
보헤미안 랩소디,20181031,25.105423,0.044,9224582,1179,204537,8,1,6,2018,1,45.099821,7824.072943,9.42,6.14,0.73,1.0
공작,20180808,24.479543,0.024,4974520,1317,99001,32,1,6,2017,1,50.247169,3777.160213,6.83,6.93,0.20,0.0
국가부도의 날,20181128,24.152268,0.017,3747952,1180,100804,32,1,6,2018,1,37.180588,3176.230508,8.12,6.50,0.79,1.0
코코,20180111,24.044174,0.015,3510017,1177,85925,8,0,13,2017,1,40.849776,2982.172472,9.32,8.00,0.64,1.0
아쿠아맨,20181219,24.139493,0.017,3491857,1285,54505,8,1,14,2018,1,64.064893,2717.398444,8.36,6.83,0.69,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
라이브 하드,20210225,14.480809,0.000,237,10,92,32,2,6,2020,1,2.576087,23.700000,8.86,6.00,0.64,1.0
윙스 오버 에베레스트,20210930,13.874534,0.000,174,10,10,24,2,14,2019,1,17.400000,17.400000,6.17,0.00,0.46,0.0
"킬링,",20210407,13.908463,0.000,125,4,53,23,3,6,2018,1,2.358491,31.250000,8.78,7.83,0.13,1.0
서유기: 재세요왕,20210930,13.883636,0.000,123,20,22,24,0,13,2020,1,5.590909,6.150000,5.67,6.00,0.27,0.0
일론 머스크: 리얼 아이언맨,20210211,13.384728,0.000,101,1,9,20,0,5,2018,1,11.222222,101.000000,5.32,0.00,0.24,0.0

In [154]:
X=df.drop(['네티즌평점','result','긍정확률'],axis=1)
y=df['result']

In [155]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
tree=DecisionTreeClassifier(random_state=0,max_depth=3)
tree.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3, random_state=0)

In [156]:
pred=tree.predict(X_test)

In [157]:
from sklearn.metrics import accuracy_score
acc3=accuracy_score(y_test,pred)
print(acc3)

0.6065573770491803

In [158]:
train_scores,test_scores=list(),list()

In [159]:
for i in range(1,20):
    DT1=DecisionTreeClassifier(max_depth=i)
    # 깊이를 증가시키면서 의사결정나무 모델 적합
    DT1.fit(X_train,y_train)
    
    # training dataset 정확도 평가
    train_att=DT1.predict(X_train)
    train_acc=accuracy_score(y_train,train_att)
    train_scores.append(train_acc)
    
    # test data 정확도 평가
    test_att=DT1.predict(X_test)
    test_acc=accuracy_score(y_test,test_att)
    test_scores.append(test_acc)
    
    # Train 정확도와 Test 정확도를 depth 개수에 따른 정확도 확인
    print('>%d train : %.3f, test : %.3f' % (i,train_acc,test_acc))

>1 train : 0.629, test : 0.594
>2 train : 0.651, test : 0.566
>3 train : 0.673, test : 0.607
>4 train : 0.715, test : 0.607
>5 train : 0.746, test : 0.578
>6 train : 0.778, test : 0.594
>7 train : 0.813, test : 0.566
>8 train : 0.857, test : 0.549
>9 train : 0.898, test : 0.602
>10 train : 0.915, test : 0.615
>11 train : 0.949, test : 0.574
>12 train : 0.972, test : 0.557
>13 train : 0.984, test : 0.561
>14 train : 0.991, test : 0.566
>15 train : 0.993, test : 0.525
>16 train : 0.998, test : 0.566
>17 train : 1.000, test : 0.578
>18 train : 1.000, test : 0.570
>19 train : 1.000, test : 0.561

- 긍정확률을 제외하게 되면 60%에 가까운 정확도가 나오긴 하지만, 이전에 비해서는 확실히 떨어진 정확도가 도출된다

In [160]:
tree.feature_importances_

array([0.07229248, 0.        , 0.        , 0.        , 0.        ,
       0.058198  , 0.        , 0.34940648, 0.12262475, 0.        ,
       0.        , 0.        , 0.29807493, 0.09940336])

In [161]:
pd.DataFrame(tree.feature_importances_.reshape((1,-1)), index=['feature_importance'])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
feature_importance,0.072292,0.0,0.0,0.0,0.0,0.058198,0.0,0.349406,0.122625,0.0,0.0,0.0,0.298075,0.099403

In [162]:
a3=pd.DataFrame(tree.feature_importances_.reshape((1,-1)),columns=X.columns, index=['feature_importance'])
a3

,개봉일,매출액,매출액점유율,관객수,스크린수,상영횟수,대표국적,등급,장르,제작연도,유형,편당관객수,스크린당관객수,평론가평점
feature_importance,0.072292,0.0,0.0,0.0,0.0,0.058198,0.0,0.349406,0.122625,0.0,0.0,0.0,0.298075,0.099403

In [163]:
b3=a3.T
b3=b3.sort_values(by='feature_importance',ascending=False)
b3

         feature_importance
등급                 0.349406
스크린당관객수            0.298075
장르                 0.122625
평론가평점              0.099403
개봉일                0.072292
상영횟수               0.058198
매출액                0.000000
매출액점유율             0.000000
관객수                0.000000
스크린수               0.000000
대표국적               0.000000
제작연도               0.000000
유형                 0.000000
편당관객수              0.000000

매출액,매출액점유율,관객수,스크린수,대표국적,제작연도,유형,편당관객수

여기서도 중요도가 전혀 없는 매출액,매출액점유율,관객수,스크린수,대표국적,제작연도,유형,편당관객수 데이터를 제거하고 다시 돌려보자

In [164]:
df.columns

Index(['개봉일', '매출액 ', '매출액점유율', '관객수 ', '스크린수 ', '상영횟수 ', '대표국적 ', '등급 ', '장르',
       '제작연도', '유형', '편당관객수', '스크린당관객수', '네티즌평점', '평론가평점', '긍정확률', 'result'],
      dtype='object')

In [165]:
df=df.drop(['긍정확률','매출액 ', '매출액점유율','관객수 ', '스크린수 ','대표국적 ','제작연도', '유형', '편당관객수'],axis=1)

In [166]:
df

                      개봉일   상영횟수   등급   장르      스크린당관객수  네티즌평점  평론가평점  result
영화명
보헤미안 랩소디         20181031  204537    1   6  7824.072943   9.42   6.14     1.0
공작               20180808   99001    1   6  3777.160213   6.83   6.93     0.0
국가부도의 날          20181128  100804    1   6  3176.230508   8.12   6.50     1.0
코코               20180111   85925    0  13  2982.172472   9.32   8.00     1.0
아쿠아맨             20181219   54505    1  14  2717.398444   8.36   6.83     1.0
...                   ...     ...  ...  ..          ...    ...    ...     ...
라이브 하드           20210225      92    2   6    23.700000   8.86   6.00     1.0
윙스 오버 에베레스트      20210930      10    2  14    17.400000   6.17   0.00     0.0
킬링,              20210407      53    3   6    31.250000   8.78   7.83     1.0
서유기: 재세요왕        20210930      22    0  13     6.150000   5.67   6.00     0.0
일론 머스크: 리얼 아이언맨  20210211       9    0   5   101.000000   5.32   0.00     0.0

[812 rows x 8 columns]

In [167]:
X=df.drop(['네티즌평점','result'],axis=1)
y=df['result']

In [168]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
tree=DecisionTreeClassifier(random_state=0,max_depth=3)
tree.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3, random_state=0)

In [169]:
pred=tree.predict(X_test)

In [170]:
from sklearn.metrics import accuracy_score
acc4=accuracy_score(y_test,pred)
print(acc4)

0.6065573770491803

In [171]:
tree.feature_importances_

array([0.07229248, 0.058198  , 0.34940648, 0.12262475, 0.29807493,
       0.09940336])

In [172]:
pd.DataFrame(tree.feature_importances_.reshape((1,-1)), index=['feature_importance'])

                           0         1         2         3         4         5
feature_importance  0.072292  0.058198  0.349406  0.122625  0.298075  0.099403

In [173]:
a4=pd.DataFrame(tree.feature_importances_.reshape((1,-1)),columns=X.columns, index=['feature_importance'])
a4

                         개봉일     상영횟수        등급         장르   스크린당관객수     평론가평점
feature_importance  0.072292  0.058198  0.349406  0.122625  0.298075  0.099403

In [174]:
b4=a4.T
b4=b4.sort_values(by='feature_importance',ascending=False)
b4

         feature_importance
등급                 0.349406
스크린당관객수            0.298075
장르                 0.122625
평론가평점              0.099403
개봉일                0.072292
상영횟수               0.058198

다음과 같은 결과가 나온 것을 확인할 수 있다. 
- 감성분석 데이터를 제외하고 나면, 관람 등급이 가장 많은 영향을 미치고, 스크린당 관객수, 장르, 평론가 평점 순으로 영향을 미치는 것을 알 수 있다.

In [175]:
acc, acc2, acc3, acc4

(0.7540983606557377,
 0.7581967213114754,
 0.6065573770491803,
 0.6065573770491803)

In [176]:
print('전체 데이터를 기준으로 했을 때의 정확도 : ',acc)
print('전체 데이터중 중요도 0 데이터 제외 정확도 : ',acc2)
print('감성분석 칼럼 제거 후 전체 데이터를 기준으로 했을 때의 정확도 : ',acc3)
print('감성분석 칼럼 제거 후 전체 데이터중 중요도 0 데이터 제외 정확도 : ',acc4)

전체 데이터를 기준으로 했을 때의 정확도 :  0.7540983606557377
전체 데이터중 중요도 0 데이터 제외 정확도 :  0.7581967213114754
감성분석 칼럼 제거 후 전체 데이터를 기준으로 했을 때의 정확도 :  0.6065573770491803
감성분석 칼럼 제거 후 전체 데이터중 중요도 0 데이터 제외 정확도 :  0.6065573770491803